#./django-docker/docker-compose.yml
version: '3.7'

services:

  redis:
    image: redis:7.0.0-alpine

  web:
    build:
        context: .
        dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:3000
    volumes:
      - .:/opt/
    ports:
      - 40:8000
    env_file:
      - ./.env
    depends_on:
      - redis
    networks:
      - app-network

  # In order to have a task executed without terminal
  celery:
    build: .
    command: celery -A main worker -l INFO
    volumes:
      - .:/code
    depends_on:
      - redis

  # To run the command inside docker
  celery-beat:
    build: .
    command: celery -A main beat -l INFO
    volumes:
      - .:/code
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      - web

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
