#./django-docker/docker-compose.yml
version: '3.7'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  redis:
    image: redis:7.0.0-alpine

  web:
    build:
        context: .
        dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:4000
    volumes:
      - .:/opt/
    ports:
      - 40:4000
    env_file:
      - ./.env
    depends_on:
      - redis
      - db

  # In order to have a task executed without terminal
  celery:
    build: .
    command: celery -A main worker -l INFO
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  # To run the command inside docker
  celery-beat:
    build: .
    command: celery -A main beat -l INFO
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      - web

volumes:
  postgres_data:
